[package]
name = "block_time"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
chrono = { version = "0.4.42", features = ["serde"] }
serde.workspace = true
zela-std.workspace = true
log = "0.4.28"
solana-sdk = "3.0.0"
